[package]
name = "tgt-warmup"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = { version = "0.24.0", features = ["native-tls"] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde_json = "1.0.128"
